### ISSUE TITLE
Add support for unit testing

### ISSUE THREAD

**Issue by acolson** [GasStationTV/angular-coding-exercise#18]
This was thrown around during our initial discussion but there could be value allowing candidates to write their own tests using mocha.

**Comment by davezuko** [comment]
Just made a PR for this... I've never used Karma/etc. with Webpack, so the functionality can definitely be improved (i.e., how do we go about re-running tests?). We'll also need to document this in the README.

**Comment by davezuko** [comment]
I'd like to close this ticket, but we should document the test suite before doing so.

**Comment by davezuko** [comment]
Added basic documentation to README in https://github.com/GasStationTV/angular-coding-exercise/commit/4dcf0d42ea8f1b654c59c9ce4873a39c1dee5692 - closing issue.
