### ISSUE TITLE
Open inlined Webpack server URL automatically...

### ISSUE THREAD

**Issue by resistdesign** [GasStationTV/angular-coding-exercise#22]
The inlined Webpack development server URL should be opened automatically and possibly remove or update this section of the ReadMe: https://github.com/GasStationTV/angular-coding-exercise#cannot-find-inlined-webpack-development-server

**Comment by davezuko** [comment]
I tried this but was only able to get the webpage to open _before_ the build was complete, so you had to reload the page. If somebody more skilled in bash wants to take a stab at it that would be great.

**Comment by resistdesign** [comment]
You're right, this is not possible without a more complicated build system or using OS specific commands.
