### ISSUE TITLE
Remove character list from sidebar

### ISSUE THREAD

**Issue by davezuko** [GasStationTV/angular-coding-exercise#30]
While it made sense for us to have this for demonstration purposes, I think it influences and boxes candidates in too much. We should still provide some initial boilerplate for them, but it should have less structure than what exists currently.

**Comment by Aourin** [comment]
I am okay with this. We don't really need to have all of this in the application and we should leave things more open.

**Comment by davezuko** [comment]
This has been removed as of https://github.com/GasStationTV/angular-coding-exercise/commit/350e0c6812697b385785c2f3f5df6d7891f6988e

**Comment by Aourin** [comment]
Leaving a directive might still be helpful. It doesn't need to be loaded or implemented, but it might be a good starting point for some of the more inexperienced developers.

**Comment by davezuko** [comment]
Yeah I should have probably left it there, you're right.
