### ISSUE TITLE
Status bar should be a directive

### ISSUE THREAD

**Issue by davezuko** [GasStationTV/angular-coding-exercise#37]
Since we removed the character list and now only have one directive, we should make the status bar a directive to demonstrate how our pages are typically laid out. Thoughts? It would have a very simple binding of connection state (loading, loaded, error) and display the status accordingly.

**Comment by davezuko** [comment]
In case we want to go forward with this, I've already created a PR for it: https://github.com/GasStationTV/angular-coding-exercise/pull/38

**Comment by Aourin** [comment]
I think thats a good idea. It is something already in the app and will be in the app.

**Comment by davezuko** [comment]
Cool, let's merge that PR then.

**Comment by Aourin** [comment]
https://github.com/GasStationTV/angular-coding-exercise/pull/38
