### ISSUE TITLE
Travis CI Failures When Developing with Auth Key

### ISSUE THREAD

**Issue by Aourin** [GasStationTV/angular-coding-exercise#43]
After initial stage of setting up an application and setting up authentication, builds/future PRs will fail due to the nature of missing AUTH_KEYS. We should probably find a good solution to ensure that everything properly runs in that state.

**Comment by davezuko** [comment]
I considered just putting our public auth key out there since it's unlikely that we'll ever hit the rate limit, but you're right that this is an issue. Maybe webpack has a conditional require/import that we can use?
